### ISSUE TITLE
Merge with ember-changeset-validations

### ISSUE THREAD

**Issue by sandstrom** [skaterdav85/ember-changeset-conditional-validations#1]
Awesome functionality! ⛵️ 

Would you be willing to consider a merge with [ember-changeset-validations](https://github.com/DockYard/ember-changeset-validations)? 

This functionality is already spread across both [ember-changeset](https://github.com/DockYard/ember-changeset) and [ember-changeset-validations](https://github.com/DockYard/ember-changeset-validations).

Three separate libraries to cover essentially one thing seems a bit excessive. I think all three are awesome, but that they would benefit from being in one package. It would also aid discovery, right now someone may discover only `ember-changeset` but won't be aware of this library.

Here is one example of another library being merged into ember-changeset-validations:
https://github.com/DockYard/ember-changeset-validations/pull/131

**Comment by skaterdav85** [comment]
Thanks! Sure, I can make a PR this weekend. Do you manage ember-changeset-validations?

**Comment by sandstrom** [comment]
@skaterdav85 Nope I have no connection to it 😄 

Get in touch with someone on that repo first, to see whether they'd be open to it (I hope they will!).

**Comment by skaterdav85** [comment]
I think if the maintainers of ember-changeset-validations want to do that, that's cool, but I'm fine with it being a separate addon. People will probably google for "ember changeset conditional validation" and this package will come up.
