### ISSUE TITLE
get() fails with boolean values

### ISSUE THREAD

**Issue by Henridv** [skaterdav85/ember-changeset-conditional-validations#10]
When a change happens on a boolean value this.get() will return true when the value was first true and changes to false.

**Comment by skaterdav85** [comment]
can you provide an example?

**Comment by Henridv** [comment]
e.g. when the property being fetched is a boolean and was first `true`, then changes to `false`, `this.get('property')` will still return `true` because of this line `true`:

https://github.com/skaterdav85/ember-changeset-conditional-validations/blob/1f377f4e38bc97e59ee59a67ded86318b1180b30/addon/validators/sometimes.js#L8

**Comment by skaterdav85** [comment]
Would you be able to create a failing test here https://github.com/skaterdav85/ember-changeset-conditional-validations/blob/master/tests/unit/validators/sometimes-test.js ?

or copy a code snippet on this issue that will produce the problem?

**Comment by Henridv** [comment]
I created the failing test here:

https://github.com/Henridv/ember-changeset-conditional-validations/blob/c863af4e487feb6671342177490ff8216e663271/tests/unit/validators/sometimes-test.js#L184

**Comment by skaterdav85** [comment]
Can you make a PR? If you want to write the implementation as well, that'd be awesome :). I may not be able to get to it for another couple weeks as I am going on vacation.

**Comment by skaterdav85** [comment]
Released in 0.4.2
