### ISSUE TITLE
Using static and conditional validators

### ISSUE THREAD

**Issue by billdami** [skaterdav85/ember-changeset-conditional-validations#9]
Is there a method by which conditional validations AND static (always present) validations could be applied to a property? E.g. I want to ALWAYS validate that a property is a number, but conditionally validate that the number is greater than 5. 

I was thinking this format should work:
```js
{
  myProp: [
    validateNumber({integer: true}),
    validateSometimes([validateNumber({gt: 5})], function() { /* ... */ })
  ]
}
```

But this throws errors:
```
TypeError: validator is not a function
    at handle-multiple-validations.js:53
```

**Comment by billdami** [comment]
Sure, I'll take a stab at if I get some time. 

My concern is that I don't know if there is a way to allow a format like that without there being changes to ember-changeset-validations itself. Because it seems that it will only allow for an array of validators that is a single level deep, (i.e. it won't allow for nested arrays of validators) and `validateSometimes()` needs to return an array.

So maybe the PR is really needed on ember-changeset-validations such that it will recursively iterate over a an array of validators, and then the current `validateSometimes()` would just work?

**Comment by skaterdav85** [comment]
Actually, it might currently work without any changes like this:

```js
{
  myProp: [
    validateNumber({integer: true}),
    ...validateSometimes([validateNumber({gt: 5})], function() { /* ... */ })
  ]
}
```

Notice the spreading. `validateSometimes` returns an array of validators, each guarded by the condition function. See here: https://github.com/skaterdav85/ember-changeset-conditional-validations/blob/master/addon/validators/sometimes.js#L12

Give that a try and let me know how it works out. :)

**Comment by billdami** [comment]
@skaterdav85 Yes, it looks like this works! Might  be a good tip to note in the documentation. :-)

Thanks!

**Comment by skaterdav85** [comment]
@billdami Version 0.5.0 has some updates that improve the API, specifically around your use case, thanks to @sovietspaceship :) 

https://github.com/skaterdav85/ember-changeset-conditional-validations#combining-validations-with-conditional-validations
